services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: returns-sql-server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Hayeja123! # SQL Server requires a strong password
      - MSSQL_PID=Developer
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data: