spring:
  application:
    name: returns-orchestrator

  r2dbc:
    # Use double quotes and verify the ? and &
    url: "r2dbc:mssql://localhost:1433/returns_db?encrypt=true&trustServerCertificate=true"
    username: sa
    password: Hayeja123!
    pool:
      initial-size: 5
      max-size: 20

  sql:
    init:
      mode: always
      separator: ";" # Explicitly tells Spring where one command ends and the next begins

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: returns-group
      auto-offset-reset: earliest
      # These two lines tell Spring how to read the raw bytes from Kafka
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      # This is the security 'trust' setting
      spring.json.trusted.packages: "com.jhayes.returns.domain.model"

logging:
  level:
    root: INFO
    org.springframework.data.r2dbc: DEBUG
    com.jhayes.returns: DEBUG