spring:
  application:
    name: returns-orchestrator

  r2dbc:
    # Use double quotes and verify the ? and &
    url: "r2dbc:mssql://localhost:1433/returns_db?encrypt=true&trustServerCertificate=true"
    username: sa
    password: Hayeja123!
    pool:
      initial-size: 5
      max-size: 20

  sql:
    init:
      mode: always
      separator: ";" # Explicitly tell Spring where one command ends and the next begins

logging:
  level:
    root: INFO
    org.springframework.data.r2dbc: DEBUG
    com.jhayes.returns: DEBUG