server:
  port: 8081

spring:
  application:
    name: carrier-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: carrier-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        # 1. Trust the entire root package to be safe
        spring.json.trusted.packages: "com.jhayes.returns.*"
        # 2. The Bridge: Maps the OLD package name to the NEW package name
        spring.json.type.mapping: "com.jhayes.returns.domain.model.ReturnInitiatedEvent:com.jhayes.returns.event.ReturnInitiatedEvent"